name: Fern Scribe Documentation Assistant

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  fern-scribe:
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'fern-scribe')) ||
      (github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: .github/scripts/package.json

      - name: Install dependencies
        run: |
          cd .github/scripts
          npm install

      - name: Run Fern Scribe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TURBOPUFFER_API_KEY: ${{ secrets.TURBOPUFFER_API_KEY }}
          TURBOPUFFER_ENDPOINT: ${{ secrets.TURBOPUFFER_ENDPOINT }}
          TURBOPUFFER_NAMESPACE: ${{ secrets.TURBOPUFFER_NAMESPACE }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          EVENT_TYPE: ${{ github.event_name }}
          # Issue-specific variables
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          # PR-specific variables
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          cd .github/scripts
          node fern-scribe.js

      - name: Comment on success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const isIssue = context.eventName === 'issues';
            const isPR = context.eventName === 'pull_request';
            
            const successMessage = isIssue 
              ? '🌿 **Fern Scribe is working on your request!**\n\nI\'ve analyzed your documentation request and am preparing file updates. A draft PR will be created shortly with the proposed changes.\n\n*Powered by AI and TurboBuffer file discovery*'
              : '🌿 **Fern Scribe has analyzed your PR!**\n\nI\'ve automatically reviewed your documentation changes and checked for potential conflicts with existing content. Check the comments above for any recommendations.\n\n*Powered by AI and TurboBuffer content analysis*';
            
            if (isIssue) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: successMessage
              });
            } else if (isPR) {
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: successMessage
              });
            }

      - name: Comment on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const isIssue = context.eventName === 'issues';
            const isPR = context.eventName === 'pull_request';
            
            const errorMessage = isIssue
              ? '❌ **Fern Scribe encountered an error**\n\nThere was an issue processing your documentation request. Please check the action logs and try again.\n\nIf the problem persists, please contact the maintainers.'
              : '❌ **Fern Scribe encountered an error**\n\nThere was an issue automatically analyzing your PR for documentation conflicts. Please check the action logs.\n\nIf the problem persists, please contact the maintainers.';
            
            if (isIssue) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: errorMessage
              });
            } else if (isPR) {
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: errorMessage
              });
            }